parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony2_1_3
    database_user: root
    database_password: admin
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: d2a22342e77133a2a881039e29fa97b41
    database_path: null
